// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdjzqwtrgoalhwozqjhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkanpxd3RyZ29hbGh3b3pxamhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzE5ODQsImV4cCI6MjA2MzYwNzk4NH0.BoKp5bx7AmAbDMM2Lpx1wtHKpWOjLLQrxt9m8vOcHqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);